In [1]:
import polars as pl

lf = pl.scan_parquet("../data/raw/yellow_tripdata_2025-01.parquet") #lazy scan - loads on collect()
df = lf.collect()

df = df.with_columns(
    ((pl.col("tpep_dropoff_datetime") - pl.col("tpep_pickup_datetime"))
        .dt.total_seconds() /60).alias("duration_min")
)

payment_type_map = {
    0:"flex_fare_trip",
    1:"credit_card",
    2:"cash",
    3:"no_charge",
    4:"dispute",
    5:"unknown",
    6:"voided_trip",
       }



df = df.with_columns(
    pl.col("payment_type")
        .replace_strict(payment_type_map, default=None)
        .alias("payment_type")

In [2]:
df.schema

Schema([('VendorID', Int32),
        ('tpep_pickup_datetime', Datetime(time_unit='us', time_zone=None)),
        ('tpep_dropoff_datetime', Datetime(time_unit='us', time_zone=None)),
        ('passenger_count', Int64),
        ('trip_distance', Float64),
        ('RatecodeID', Int64),
        ('store_and_fwd_flag', String),
        ('PULocationID', Int32),
        ('DOLocationID', Int32),
        ('payment_type', Int64),
        ('fare_amount', Float64),
        ('extra', Float64),
        ('mta_tax', Float64),
        ('tip_amount', Float64),
        ('tolls_amount', Float64),
        ('improvement_surcharge', Float64),
        ('total_amount', Float64),
        ('congestion_surcharge', Float64),
        ('Airport_fee', Float64),
        ('cbd_congestion_fee', Float64),
        ('duration_min', Float64)])

In [3]:
df.filter(pl.col("duration_min") > 0)

shape: (3_473_175, 21)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ congestio ┆ Airport_f ┆ cbd_conge ┆ duration_ │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ n_surchar ┆ ee        ┆ stion_fee ┆ min       │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ge        ┆ ---       ┆ ---       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆           ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 2.5       ┆ 0.0       ┆ 0.0       ┆ 8.35      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:18:38  ┆ 00:26:59  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 2.5       ┆ 0.0       ┆ 0.0       ┆ 2.55      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:32:40  ┆ 00:35:13  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 2.5       ┆ 0.0       ┆ 0.0       ┆ 1.95      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:44:04  ┆ 00:46:01  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-0 ┆ 2025-01-0 ┆ 3         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 5.566667  │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:14:27  ┆ 00:20:01  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-0 ┆ 2025-01-0 ┆ 3         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 3.533333  │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:21:34  ┆ 00:25:06  ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2        ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.75      ┆ 14.683333 │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:01:48  ┆ 23:16:29  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.75      ┆ 26.966667 │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:50:29  ┆ 00:17:27  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.75      ┆ 16.033333 │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:26:59  ┆ 23:43:01  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.75      ┆ 20.3      │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:14:34  ┆ 23:34:52  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ 10.75     │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:56:42  ┆ 00:07:27  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
df.group_by(pl.col("tpep_pickup_datetime").dt.hour().alias("hour")) \
    .agg(pl.col("duration_min").mean().alias("avg_duration")) \
    .sort("hour")

shape: (24, 2)
┌──────┬──────────────┐
│ hour ┆ avg_duration │
│ ---  ┆ ---          │
│ i8   ┆ f64          │
╞══════╪══════════════╡
│ 0    ┆ 13.785256    │
│ 1    ┆ 12.06919     │
│ 2    ┆ 12.763833    │
│ 3    ┆ 12.500513    │
│ 4    ┆ 14.155369    │
│ …    ┆ …            │
│ 19   ┆ 13.991177    │
│ 20   ┆ 13.681685    │
│ 21   ┆ 13.842334    │
│ 22   ┆ 14.097557    │
│ 23   ┆ 14.025077    │
└──────┴──────────────┘

In [5]:
payment_type_map = {
    0:"flex_fare_trip",
    1:"credit_card",
    2:"cash",
    3:"no_charge",
    4:"dispute",
    5:"unknown",
    6:"voided_trip",
       }

df = df.with_columns(
    pl.col("payment_type")
        .replace_strict(payment_type_map, default=None)
        .alias("payment_type")
)

df["payment_type"].value_counts()

shape: (6, 2)
┌────────────────┬─────────┐
│ payment_type   ┆ count   │
│ ---            ┆ ---     │
│ str            ┆ u32     │
╞════════════════╪═════════╡
│ flex_fare_trip ┆ 540149  │
│ no_charge      ┆ 23773   │
│ dispute        ┆ 76481   │
│ unknown        ┆ 1       │
│ cash           ┆ 390429  │
│ credit_card    ┆ 2444393 │
└────────────────┴─────────┘