In [1]:
import polars as pl

pl.Config.set_tbl_rows(24)
pl.Config.save()  # saves to ~/.config/polars/config.json

'{"environment":{"POLARS_ENGINE_AFFINITY":null,"POLARS_FMT_MAX_COLS":null,"POLARS_FMT_MAX_ROWS":"24","POLARS_FMT_NUM_DECIMAL":null,"POLARS_FMT_NUM_GROUP_SEPARATOR":null,"POLARS_FMT_NUM_LEN":null,"POLARS_FMT_STR_LEN":null,"POLARS_FMT_TABLE_CELL_ALIGNMENT":null,"POLARS_FMT_TABLE_CELL_LIST_LEN":null,"POLARS_FMT_TABLE_CELL_NUMERIC_ALIGNMENT":null,"POLARS_FMT_TABLE_DATAFRAME_SHAPE_BELOW":null,"POLARS_FMT_TABLE_FORMATTING":null,"POLARS_FMT_TABLE_HIDE_COLUMN_DATA_TYPES":null,"POLARS_FMT_TABLE_HIDE_COLUMN_NAMES":null,"POLARS_FMT_TABLE_HIDE_COLUMN_SEPARATOR":null,"POLARS_FMT_TABLE_HIDE_DATAFRAME_SHAPE_INFORMATION":null,"POLARS_FMT_TABLE_INLINE_COLUMN_DATA_TYPE":null,"POLARS_FMT_TABLE_ROUNDED_CORNERS":null,"POLARS_MAX_EXPR_DEPTH":null,"POLARS_STREAMING_CHUNK_SIZE":null,"POLARS_TABLE_WIDTH":null,"POLARS_VERBOSE":null,"POLARS_WARN_UNSTABLE":null},"direct":{"set_fmt_float":"mixed","set_float_precision":null,"set_thousands_separator":"","set_decimal_separator":".","set_trim_decimal_zeros":false}}'

In [2]:
lf = pl.scan_parquet(
    "../data/raw/yellow_tripdata_2025-01.parquet"
)  # lazy scan - loads on collect()
df = lf.collect()
df.columns = [c.lower() for c in df.columns]
df = df.rename(
    {
        "ratecodeid": "rate_code_id",
        "vendorid": "vendor_id",
        "pulocationid": "pickup_location_id",
        "dolocationid": "dropoff_location_id",
    }
)

In [3]:
zones = pl.read_csv("../data/raw/taxi_zone_lookup.csv")
df = df.join(
    zones.rename({"LocationID": "pickup_location_id"}),
    on="pickup_location_id",
    how="left",
)

In [4]:
zones.filter(pl.col("Zone").str.contains("Airport"))

shape: (3, 4)
┌────────────┬─────────┬───────────────────┬──────────────┐
│ LocationID ┆ Borough ┆ Zone              ┆ service_zone │
│ ---        ┆ ---     ┆ ---               ┆ ---          │
│ i64        ┆ str     ┆ str               ┆ str          │
╞════════════╪═════════╪═══════════════════╪══════════════╡
│ 1          ┆ EWR     ┆ Newark Airport    ┆ EWR          │
│ 132        ┆ Queens  ┆ JFK Airport       ┆ Airports     │
│ 138        ┆ Queens  ┆ LaGuardia Airport ┆ Airports     │
└────────────┴─────────┴───────────────────┴──────────────┘

In [5]:
# Build model columns
store_and_fwd_bin = {
    "N": 0,
    "Y": 1,
}

df = df.with_columns(
    # Create duration_sec column from dropoff and pickup times
    (
        (pl.col("tpep_dropoff_datetime") - pl.col("tpep_pickup_datetime")).dt.total_seconds() / 60
    ).alias("duration_min"),
    # Convert Y/N flagging to 1-hot encoding
    (
        pl.col("store_and_fwd_flag")
        .replace_strict(store_and_fwd_bin, default=None)
        .alias("store_and_fwd_flag")
    ),
)

In [6]:
# %%script echo skipping
# print("This code will be completely ignored.")
# EDA ONLY — drop before modeling
# Build readability columns
vendor_id_map = {
    1: "Creative Mobile Technologies LLC",
    2: "Curb Mobility, LLC",
    6: "Myle Technologies Inc",
    7: "Helix",
}

payment_type_map = {
    0: "flex_fare_trip",
    1: "credit_card",
    2: "cash",
    3: "no_charge",
    4: "dispute",
    5: "unknown",
    6: "voided_trip",
}


rate_code_map = {
    1: "standard_rate",
    2: "jfk",
    3: "newark",
    4: "nassau_or_winchester",
    5: "negotiated_fare",
    6: "group_ride",
    99: "null_or_unknown",
}

df = df.with_columns(
    # Create a new column with readable payment type
    (
        pl.col("payment_type")
        .replace_strict(payment_type_map, default=None)
        .alias("payment_type_str")
    ),
    # Create a new column with readable rate code
    (pl.col("rate_code_id").replace_strict(rate_code_map, default=None).alias("rate_code_str")),
    # Create a new column with readable vendor ID
    (pl.col("vendor_id").replace_strict(vendor_id_map, default=None).alias("vendor_id_str")),
)

In [7]:
df.schema

Schema([('vendor_id', Int32),
        ('tpep_pickup_datetime', Datetime(time_unit='us', time_zone=None)),
        ('tpep_dropoff_datetime', Datetime(time_unit='us', time_zone=None)),
        ('passenger_count', Int64),
        ('trip_distance', Float64),
        ('rate_code_id', Int64),
        ('store_and_fwd_flag', Int64),
        ('pickup_location_id', Int32),
        ('dropoff_location_id', Int32),
        ('payment_type', Int64),
        ('fare_amount', Float64),
        ('extra', Float64),
        ('mta_tax', Float64),
        ('tip_amount', Float64),
        ('tolls_amount', Float64),
        ('improvement_surcharge', Float64),
        ('total_amount', Float64),
        ('congestion_surcharge', Float64),
        ('airport_fee', Float64),
        ('cbd_congestion_fee', Float64),
        ('Borough', String),
        ('Zone', String),
        ('service_zone', String),
        ('duration_min', Float64),
        ('payment_type_str', String),
        ('rate_code_str', String),
        ('vendor_id_str', String)])

In [8]:
# Filter out rows where the duration is less than or equal to 0
df.filter(pl.col("duration_min") > 0)

shape: (3_473_175, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ vendor_id ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ duration_ ┆ payment_t ┆ rate_code ┆ vendor_i │
│ ---       ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ min       ┆ ype_str   ┆ _str      ┆ d_str    │
│ i32       ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ ---       ┆ ---       ┆ i64       ┆   ┆ f64       ┆ str       ┆ str       ┆ str      │
│           ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 8.35      ┆ credit_ca ┆ standard_ ┆ Creative │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rd        ┆ rate      ┆ Mobile   │
│           ┆ 00:18:38  ┆ 00:26:59  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 2.55      ┆ credit_ca ┆ standard_ ┆ Creative │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rd        ┆ rate      ┆ Mobile   │
│           ┆ 00:32:40  ┆ 00:35:13  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 1.95      ┆ credit_ca ┆ standard_ ┆ Creative │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rd        ┆ rate      ┆ Mobile   │
│           ┆ 00:44:04  ┆ 00:46:01  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 3         ┆ … ┆ 5.566667  ┆ cash      ┆ standard_ ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆ rate      ┆ ility,   │
│           ┆ 00:14:27  ┆ 00:20:01  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 3         ┆ … ┆ 3.533333  ┆ cash      ┆ standard_ ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆ rate      ┆ ility,   │
│           ┆ 00:21:34  ┆ 00:25:06  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 2         ┆ … ┆ 20.033333 ┆ cash      ┆ standard_ ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆ rate      ┆ ility,   │
│           ┆ 00:48:24  ┆ 01:08:26  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 0         ┆ … ┆ 1.466667  ┆ credit_ca ┆ standard_ ┆ Creative │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rd        ┆ rate      ┆ Mobile   │
│           ┆ 00:14:47  ┆ 00:16:15  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 0         ┆ … ┆ 12.4      ┆ credit_ca ┆ standard_ ┆ Creative │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rd        ┆ rate      ┆ Mobile   │
│           ┆ 00:39:27  ┆ 00:51:51  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 0         ┆ … ┆ 19.666667 ┆ credit_ca ┆ standard_ ┆ Creative │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rd        ┆ rate      ┆ Mobile   │
│           ┆ 00:53:43  ┆ 01:13:23  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 9.566667  ┆ cash      ┆ standard_ ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆ rate      ┆ ility,   │
│           ┆ 00:00:02  ┆ 00:09:36  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 7.6       ┆ cash      ┆ standard_ ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆ rate      ┆ ility,   │
│           ┆ 00:20:28  ┆ 00:28:04  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ 3.416667  ┆ credit_ca ┆ standard_ ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ rd        ┆ rate      ┆ ility,   │
│           ┆ 00:33:58  ┆ 00:37:23  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2         ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ 11.016667 ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:52:34  ┆ 00:03:35  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ 12.05     ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:32:04  ┆ 23:44:07  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ 5.95      ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:58:20  ┆ 00:04:17  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ 7.833333  ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:38:25  ┆ 23:46:15  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ 8.433333  ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:26:03  ┆ 23:34:29  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ 15.0      ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:21:00  ┆ 23:36:00  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ 13.55     ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:26:31  ┆ 23:40:04  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ 14.683333 ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:01:48  ┆ 23:16:29  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ 26.966667 ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:50:29  ┆ 00:17:27  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ 16.033333 ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:26:59  ┆ 23:43:01  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-01-3 ┆ null      ┆ … ┆ 20.3      ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:14:34  ┆ 23:34:52  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
│ 2         ┆ 2025-01-3 ┆ 2025-02-0 ┆ null      ┆ … ┆ 10.75     ┆ flex_fare ┆ null      ┆ Curb Mob │
│           ┆ 1         ┆ 1         ┆           ┆   ┆           ┆ _trip     ┆           ┆ ility,   │
│           ┆ 23:56:42  ┆ 00:07:27  ┆           ┆   ┆           ┆           ┆           ┆ LLC      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df.describe()

shape: (9, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ vendor_id ┆ tpep_pick ┆ tpep_drop ┆ … ┆ duration_ ┆ payment_t ┆ rate_code ┆ vendor_i │
│ ---       ┆ ---       ┆ up_dateti ┆ off_datet ┆   ┆ min       ┆ ype_str   ┆ _str      ┆ d_str    │
│ str       ┆ f64       ┆ me        ┆ ime       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ ---       ┆ ---       ┆   ┆ f64       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 3.475226e ┆ 3475226   ┆ 3475226   ┆ … ┆ 3.475226e ┆ 3475226   ┆ 2935077   ┆ 3475226  │
│           ┆ 6         ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 0         ┆ 540149    ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 1.785428  ┆ 2025-01-1 ┆ 2025-01-1 ┆ … ┆ 15.018116 ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 7 11:02:5 ┆ 7 11:17:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 5.910964  ┆ 6.997901  ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 0.426328  ┆ null      ┆ null      ┆ … ┆ 38.713582 ┆ null      ┆ null      ┆ null     │
│ min       ┆ 1.0       ┆ 2024-12-3 ┆ 2024-12-1 ┆ … ┆ -51472.31 ┆ cash      ┆ group_rid ┆ Creative │
│           ┆           ┆ 1         ┆ 8         ┆   ┆ 6667      ┆           ┆ e         ┆ Mobile   │
│           ┆           ┆ 20:47:55  ┆ 07:52:40  ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 25%       ┆ 2.0       ┆ 2025-01-1 ┆ 2025-01-1 ┆ … ┆ 7.283333  ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 0         ┆ 0         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 07:59:01  ┆ 08:15:29  ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 2.0       ┆ 2025-01-1 ┆ 2025-01-1 ┆ … ┆ 11.7      ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 7         ┆ 7         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 15:41:34  ┆ 15:59:34  ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 2.0       ┆ 2025-01-2 ┆ 2025-01-2 ┆ … ┆ 18.333333 ┆ null      ┆ null      ┆ null     │
│           ┆           ┆ 4         ┆ 4         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 19:34:06  ┆ 19:48:31  ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 7.0       ┆ 2025-02-0 ┆ 2025-02-0 ┆ … ┆ 5626.3166 ┆ unknown   ┆ standard_ ┆ Myle Tec │
│           ┆           ┆ 1         ┆ 1         ┆   ┆ 67        ┆           ┆ rate      ┆ hnologie │
│           ┆           ┆ 00:00:44  ┆ 23:44:11  ┆   ┆           ┆           ┆           ┆ s Inc    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
df.filter(pl.col("duration_min") < 0).sort("duration_min")

shape: (124, 27)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ vendor_id ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ duration_ ┆ payment_t ┆ rate_code ┆ vendor_i │
│ ---       ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ min       ┆ ype_str   ┆ _str      ┆ d_str    │
│ i32       ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ ---       ┆ ---       ┆ i64       ┆   ┆ f64       ┆ str       ┆ str       ┆ str      │
│           ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 2025-01-2 ┆ 2024-12-1 ┆ 0         ┆ … ┆ -51472.31 ┆ credit_ca ┆ standard_ ┆ Creative │
│           ┆ 3         ┆ 8         ┆           ┆   ┆ 6667      ┆ rd        ┆ rate      ┆ Mobile   │
│           ┆ 01:44:59  ┆ 07:52:40  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ -56.03333 ┆ credit_ca ┆ null_or_u ┆ Creative │
│           ┆ 2         ┆ 2         ┆           ┆   ┆ 3         ┆ rd        ┆ nknown    ┆ Mobile   │
│           ┆ 12:26:00  ┆ 11:29:58  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 1         ┆ 2025-01-0 ┆ 2025-01-0 ┆ 1         ┆ … ┆ -54.5     ┆ credit_ca ┆ null_or_u ┆ Creative │
│           ┆ 6         ┆ 6         ┆           ┆   ┆           ┆ rd        ┆ nknown    ┆ Mobile   │
│           ┆ 16:00:00  ┆ 15:05:30  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 1         ┆ 2025-01-2 ┆ 2025-01-2 ┆ 1         ┆ … ┆ -45.01666 ┆ credit_ca ┆ null_or_u ┆ Creative │
│           ┆ 3         ┆ 3         ┆           ┆   ┆ 7         ┆ rd        ┆ nknown    ┆ Mobile   │
│           ┆ 12:30:00  ┆ 11:44:59  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 1         ┆ 2025-01-2 ┆ 2025-01-2 ┆ 1         ┆ … ┆ -29.75    ┆ credit_ca ┆ null_or_u ┆ Creative │
│           ┆ 9         ┆ 9         ┆           ┆   ┆           ┆ rd        ┆ nknown    ┆ Mobile   │
│           ┆ 14:00:00  ┆ 13:30:15  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 1         ┆ 2025-01-1 ┆ 2025-01-1 ┆ 1         ┆ … ┆ -17.2     ┆ credit_ca ┆ null_or_u ┆ Creative │
│           ┆ 5         ┆ 5         ┆           ┆   ┆           ┆ rd        ┆ nknown    ┆ Mobile   │
│           ┆ 15:00:00  ┆ 14:42:48  ┆           ┆   ┆           ┆           ┆           ┆ Technolo │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ gies L…  │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.933333 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 7         ┆ 7         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 13:01:56  ┆ 13:01:00  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.9      ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 3         ┆ 3         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 00:01:59  ┆ 00:01:05  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.85     ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 3         ┆ 3         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 13:01:51  ┆ 13:01:00  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.833333 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 9         ┆ 9         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 16:01:51  ┆ 16:01:01  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ -0.833333 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 5         ┆ 5         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 11:01:59  ┆ 11:01:09  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.816667 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 4         ┆ 4         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 14:01:56  ┆ 14:01:07  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 6         ┆ 2025-01-0 ┆ 2025-01-0 ┆ null      ┆ … ┆ -0.066667 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 6         ┆ 6         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 21:01:43  ┆ 21:01:39  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.066667 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 5         ┆ 5         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 15:01:50  ┆ 15:01:46  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.066667 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 5         ┆ 5         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 18:01:16  ┆ 18:01:12  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ -0.066667 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 3         ┆ 3         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 17:01:23  ┆ 17:01:19  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ -0.05     ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 3         ┆ 3         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 00:01:37  ┆ 00:01:34  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-0 ┆ 2025-01-0 ┆ null      ┆ … ┆ -0.033333 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 7         ┆ 7         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 13:01:14  ┆ 13:01:12  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.033333 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 5         ┆ 5         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 12:01:02  ┆ 12:01:00  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.016667 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 2         ┆ 2         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 22:01:06  ┆ 22:01:05  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.016667 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 3         ┆ 3         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 23:01:30  ┆ 23:01:29  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.016667 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 4         ┆ 4         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 11:01:44  ┆ 11:01:43  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-1 ┆ 2025-01-1 ┆ null      ┆ … ┆ -0.016667 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 6         ┆ 6         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 09:01:19  ┆ 09:01:18  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
│ 6         ┆ 2025-01-2 ┆ 2025-01-2 ┆ null      ┆ … ┆ -0.016667 ┆ flex_fare ┆ null      ┆ Myle Tec │
│           ┆ 9         ┆ 9         ┆           ┆   ┆           ┆ _trip     ┆           ┆ hnologie │
│           ┆ 10:01:29  ┆ 10:01:28  ┆           ┆   ┆           ┆           ┆           ┆ s Inc    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
# Zero column analysis -- Clean up output, i.e. pivot column names to rows with one column "count"
cols = [
    "passenger_count",
    "trip_distance",
    "duration_min",
    "fare_amount",
    "extra",
    "mta_tax",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge",
    "total_amount",
    "congestion_surcharge",
    "airport_fee",
    "cbd_congestion_fee",
]
pl.concat(
    [df.select(pl.lit(c).alias("column"), (pl.col(c) == 0).sum().alias("zero_count")) for c in cols]
)

shape: (13, 2)
┌───────────────────────┬────────────┐
│ column                ┆ zero_count │
│ ---                   ┆ ---        │
│ str                   ┆ u32        │
╞═══════════════════════╪════════════╡
│ passenger_count       ┆ 24656      │
│ trip_distance         ┆ 90893      │
│ duration_min          ┆ 1927       │
│ fare_amount           ┆ 1398       │
│ extra                 ┆ 1764424    │
│ mta_tax               ┆ 38170      │
│ tip_amount            ┆ 1118008    │
│ tolls_amount          ┆ 3259590    │
│ improvement_surcharge ┆ 37694      │
│ total_amount          ┆ 559        │
│ congestion_surcharge  ┆ 225938     │
│ airport_fee           ┆ 2706446    │
│ cbd_congestion_fee    ┆ 1222178    │
└───────────────────────┴────────────┘

In [12]:
# Tail analysis
cols = ["trip_distance", "passenger_count", "duration_min"]
cast_df = df.with_columns(pl.col(cols).cast(pl.Float64))
pl.concat(
    [
        cast_df.select(
            pl.lit(c).alias("column"),
            pl.col(c).min().alias("min"),
            pl.col(c).quantile(0.001).alias("p0.1"),
            pl.col(c).quantile(0.999).alias("p99.9"),
            pl.col(c).max().alias("max"),
        )
        for c in cols
    ]
)

shape: (3, 5)
┌─────────────────┬───────────────┬──────────┬───────────┬─────────────┐
│ column          ┆ min           ┆ p0.1     ┆ p99.9     ┆ max         │
│ ---             ┆ ---           ┆ ---      ┆ ---       ┆ ---         │
│ str             ┆ f64           ┆ f64      ┆ f64       ┆ f64         │
╞═════════════════╪═══════════════╪══════════╪═══════════╪═════════════╡
│ trip_distance   ┆ 0.0           ┆ 0.0      ┆ 28.86     ┆ 276423.57   │
│ passenger_count ┆ 0.0           ┆ 0.0      ┆ 6.0       ┆ 9.0         │
│ duration_min    ┆ -51472.316667 ┆ 0.066667 ┆ 98.266667 ┆ 5626.316667 │
└─────────────────┴───────────────┴──────────┴───────────┴─────────────┘

In [13]:
df.group_by(pl.col("tpep_pickup_datetime").dt.hour().alias("hour")).agg(
    pl.col("duration_min").mean().alias("avg_duration")
).sort("hour")

shape: (24, 2)
┌──────┬──────────────┐
│ hour ┆ avg_duration │
│ ---  ┆ ---          │
│ i8   ┆ f64          │
╞══════╪══════════════╡
│ 0    ┆ 13.785256    │
│ 1    ┆ 12.06919     │
│ 2    ┆ 12.763833    │
│ 3    ┆ 12.500513    │
│ 4    ┆ 14.155369    │
│ 5    ┆ 15.998068    │
│ 6    ┆ 15.67766     │
│ 7    ┆ 15.709326    │
│ 8    ┆ 15.574044    │
│ 9    ┆ 15.055785    │
│ 10   ┆ 14.938037    │
│ 11   ┆ 15.339699    │
│ 12   ┆ 15.270587    │
│ 13   ┆ 15.653991    │
│ 14   ┆ 16.513955    │
│ 15   ┆ 16.724708    │
│ 16   ┆ 16.738171    │
│ 17   ┆ 15.856804    │
│ 18   ┆ 14.500614    │
│ 19   ┆ 13.991177    │
│ 20   ┆ 13.681685    │
│ 21   ┆ 13.842334    │
│ 22   ┆ 14.097557    │
│ 23   ┆ 14.025077    │
└──────┴──────────────┘

In [14]:
df["payment_type"].value_counts()

shape: (6, 2)
┌──────────────┬─────────┐
│ payment_type ┆ count   │
│ ---          ┆ ---     │
│ i64          ┆ u32     │
╞══════════════╪═════════╡
│ 0            ┆ 540149  │
│ 4            ┆ 76481   │
│ 2            ┆ 390429  │
│ 5            ┆ 1       │
│ 1            ┆ 2444393 │
│ 3            ┆ 23773   │
└──────────────┴─────────┘

In [15]:
zone_counts = df["Zone"].value_counts()

# EDA Notes

### Fields Known at Pickup:

- **VendorID** - I assume this has to be the taxi proprietor
- RatecodeID
- **tpep_pickup_datetime** - goes without saying
- **passenger_count** - again, you should know how many people are getting in the car
- **store_and_fwd_flag**(?) - not sure about this one
- **PULocationID** - again, you should know where you are
- **DOLocationID** - I think there's an argument to be made about this one. You have to tell the cabby where you want to go as soon as you get in the car, so they'd have to know the drop-off location at pickup, right? It is the definition itself that is making me pause: "TLC Taxi Zone in which the taximeter was disengaged."

### Pickup/Dropoff

- Earliest pickup datetime is after the earliest dropoff datetime
  - Going to need to remove records where:
    - tpep_dropoff_datetime <= tpep_pickup_datetime

### Zero Values

- **Trip Distance:** 90,893 zero distance records
- **Passenger Count:** 24,656 zero passenger records
- **Fare Amount:** 1,398 zero passenger records (May or may not be legitimate)
  - Small population suggests that this is an error rather than legit zeros.
- **Total Amount:** 559 zero passenger records (May or may not be legitimate)
  - Small population suggests that this is an error rather than legit zeros.
  - _NOTE:_ Zero total amount population is smaller than zero fare amount population./nWarrants further investigation as this could be either:
    - The ride was actually free and the individual provided a tip or there was a categorical surcharge present
    - 559 of the 1,398 zero fare amount records should have a larger value present and the remainder were legitimate zero fare rides
- **Trip Duration:** Only 1,927 zero minute duration rides is vast difference from the 90,893 zero trip distance records
  - Could be cab starts meter after stopping for pickup and then ride is cancelled with time charged?
    - I don't live in NY, so I'm not sure how this works.

### Tail Analysis

- Trip distance has massive max error tail
  - p99.9 is only 28.86, so 276423.57 is both, per the dataset and mathematically, impossible
- Passenger count has only 18 records > 6.0 (four 7.0 records, eleven 8.0 records, and three 9.0 records)
  - Given there are millions of records, it seems wiser to just cut these out, although it is technically possible that there may have been babies present with parents or people sitting on laps illegally, just saying.
- Any negative trip duration/trip distance values can be removed from the dataset.

### Cross-Column Relationship Issues

- **Trip Duration x Trip Distance**
  - Potential problem in terms of its error tail. It's hard to say where the errors are and where some of them are just truly long trips when cross referenced with **Trip Distance.** There is a 91 mile trip where the meter ran for 5000+ minutes. Given that that is 3.5 days of usage, I doubt the time is entirely legitimate, but it is a long haul trip for sure. There are also hundreds where it ran for 300+ minutes on a 15-20 mile trip. So it's difficult to pin down where to actually remove meter errors and which are legitimate fares/trip durations.
  - Duration should have a minimum cutoff as well in relation to distance of some sort. Trips less than 1 minute seem ridiculous logically, but also, if something has a long distance then there needs to be a logical amount of trip duration for that distance.
  - _NOTE:_ Perhaps get trimmed, weighted average for time per mile travelled to determine a reasonable min/max for the cross-column relationship and remove anything that falls outside of that. I assume there are going to be accuracy issues as part of this. Could also create some sort of likelihood value of the mile/minute value and then filter based on that?
-